language: java
jdk:
  - oraclejdk8
sudo: false
script:
  -mvn --settings .travis/settings.xml clean cobertura:cobertura
after_success:
  - bash <(curl -s https://codecov.io/bash)

language: java

deploy:
  -
    provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: kasiprasad/context-spec
      tags: true
      jdk: oraclejdk8
